### ISSUE TITLE
Ensure 'become' is disabled in tasks

### ISSUE THREAD

**Issue by jonashaag** [debops/ansible-core#9]
The [Check IP address of current Ansible Controller](https://github.com/debops/ansible-core/blob/d07d9e71e6a25656df8c4111b3f46f0edb30942c/tasks/main.yml#L13) task has `become: False` set, which is required for the `SSH_CLIENT` environment variable to be set properly. Now this option does not always have an effect. To be precise, doesn't work if the `become` option has been enabled in hostvars. But the task *always requires* `become: False`.

I don't think there's a fix; I've also asked about this on the ansible-project mailing list, to no response: https://groups.google.com/forum/#!topic/ansible-project/iIW4zUNizN4

My suggestion is as follows:

1. Add a warning to the documentation to let people know it's not possible to use ansible-core if they've enabled `become` in hostvars.
2. Add an assertion before the *Check IP address of current Ansible Controller* task that makes sure we're not using become. I'm not sure how to do this, though. My initial idea is to use something along the lines of
   ```yaml
   - shell: whoami
      register: whoami

   - fail: msg="The next task requires 'become: False'. Make sure to not enable 'become' in your hostvars. Move your 'become' options to your ansible.cfg if required."
      when: whoami.stdout == "root"
   ```
   Now obviously you may want to become someone else than root, so the "root" check isn't really the correct thing to do here. I'm not sure how to find out if `become` is enabled for the current task though.
